name = "modfest-skyandsea"
mc_version = "1.20.4"

[jar]
type = "fabric"
loader = "0.15.3"
installer = "latest"

[variables]
PORT = "25565"

[launcher]
eula_args = true
nogui = true

[worlds.modfest-1-20]
datapacks = []

[[mods]]
type = "modrinth"
id = "fabric-api"
version = "0.92.0+1.20.4"

[[mods]]
type = "modrinth"
id = "fabric-language-kotlin"
version = "1.10.17+kotlin.1.9.22"

[[mods]]
type = "modrinth"
id = "modmenu"
version = "9.0.0"

[[mods]]
type = "url"
url = "https://jaskarth.com/pub/mods/player-roles-1.6.8.jar"

[[mods]]
type = "url"
url = "https://jaskarth.com/pub/mods/fireblanket-0.4.0.jar"

[[mods]]
type = "url"
url = "https://jaskarth.com/pub/mods/glowcase-1.2.1+1.20.4.jar"

[[mods]]
type = "modrinth"
id = "modernfix"
version = "5.10.2+mc1.20.4"

[[mods]]
type = "modrinth"
id = "spark"
version = "1.10.58-fabric"

[[mods]]
type = "modrinth"
id = "sodium"
version = "mc1.20.3-0.5.5"

[[mods]]
type = "modrinth"
id = "axiom"
version = "2.1.1"

[[mods]]
type = "modrinth"
id = "worldedit"
version = "7.2.18"

[[mods]]
type = "modrinth"
id = "emi"
version = "jXyglcrU"

[[mods]]
type = "modrinth"
id = "lithium"
version = "nMhjKWVE"

[[mods]]
type = "modrinth"
id = "indium"
version = "tD2IqHXC"

[[mods]]
type = "modrinth"
id = "badpackets"
version = "SvSHT7FN"

[[mods]]
type = "modrinth"
id = "yacl"
version = "3.3.1+1.20.4-fabric"

[[mods]]
type = "modrinth"
id = "smartbrainlib"
version = "1.13"

[[mods]]
type = "modrinth"
id = "cloth-config"
version = "13.0.121+fabric"

[[mods]]
type = "modrinth"
id = "geckolib"
version = "Z4SMiN06"

[markdown]
files = ["README.md"]
auto_update = false

[options]

# BEGIN SUBMISSIONS #

#[SUBMISSIONS]

# END SUBMISSIONS #
