name = "modfest-skyandsea"
mc_version = "1.20.4"

[jar]
type = "fabric"
loader = "0.15.2"
installer = "latest"

[variables]
PORT = "25565"

[launcher]
eula_args = true
nogui = true
preset_flags = "none"

[[mods]]
type = "modrinth"
id = "fabric-api"

[[mods]]
type = "modrinth"
id = "fabric-language-kotlin"

[[mods]]
type = "modrinth"
id = "modmenu"

[[mods]]
type = "url"
url = "https://jaskarth.com/pub/mods/player-roles-1.6.8.jar"

[[mods]]
type = "url"
url = "https://jaskarth.com/pub/mods/fireblanket-0.4.0.jar"

[[mods]]
type = "modrinth"
id = "modernfix"
version = "5.10.2+mc1.20.4"

[[mods]]
type = "modrinth"
id = "spark"
version = "1.10.58-fabric"

[[mods]]
type = "modrinth"
id = "sodium"

[markdown]
files = ["README.md"]
