name = "modfest-skyandsea"
version = "99b7e93dbb621083d6e56841261d7716d43bd61e"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash = "c25e256ad2b1c0a1707af89d77ee381dbaac675132a8a9eeca045cd4844ac044"
hash-format = "sha256"
metafile = false
preserve = false

[versions]
minecraft = "1.20.4"
fabric = "0.15.2"
