name = "modfest-skyandsea"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash = "d474d663cef135a9cb7a1bc9c7d58e7cb172edf1dcdf2849217b4324cfe230fa"
hash-format = "sha256"
metafile = false
preserve = false

[versions]
minecraft = "1.20.4"
fabric = "latest"
