name = "modfest-skyandsea"
version = "fd112d1fc73d3f5f96146234112c3b90f70647ee"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash = "c25e256ad2b1c0a1707af89d77ee381dbaac675132a8a9eeca045cd4844ac044"
hash-format = "sha256"
metafile = false
preserve = false

[versions]
fabric = "0.15.2"
minecraft = "1.20.4"
