name = "modfest-skyandsea"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash = "ea1fbb221e0e029d4667f868538fdc13f548261930bf5028c46e396dd5b9e526"
hash-format = "sha256"
metafile = false
preserve = false

[versions]
fabric = "0.15.3"
minecraft = "1.20.4"
