name = "modfest-skyandsea"
version = "c594b19ea64c7102e8f1e91e7255e56be1a4ff14"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash = "deb7456d246ef96d2bf4f27e5671ac01e0d99d07253eeaf5db6136d16d2d4bbd"
hash-format = "sha256"
metafile = false
preserve = false

[versions]
fabric = "0.15.2"
minecraft = "1.20.4"
