name = "modfest-skyandsea"
version = "311c77c989d401760f1086bb5fcea0ace2b5b6ba"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash = "74dea71c6e9e740ce83df1fef4b8e20de9ba6f2f37d19b3c7a17fce206d84c52"
hash-format = "sha256"
metafile = false
preserve = false

[versions]
minecraft = "1.20.4"
fabric = "0.15.2"
