name = "modfest-skyandsea"
version = "e6fc328279b1f0d971467a548b06560ddff640ca"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash = "41b7399cb5e25f94fa807cf1c8fcf135c129fd969333a70fb56c76616ec7aaee"
hash-format = "sha256"
metafile = false
preserve = false

[versions]
fabric = "0.15.3"
minecraft = "1.20.4"
