name = "modfest-skyandsea"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash = "28840882243347d998102d0ed498f035f4472b1f6ced22eb924588f5556caa29"
hash-format = "sha256"
metafile = false
preserve = false

[versions]
minecraft = "1.20.4"
fabric = "0.15.3"
