name = "modfest-skyandsea"
version = "50f7d0a95e0cc5b3b5ebedbd1080da756b1b9387"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash = "59342cbf2d455f5a95138703e6a98363555ce8a38a18ffeb43c278c469a54c85"
hash-format = "sha256"
metafile = false
preserve = false

[versions]
minecraft = "1.20.4"
fabric = "0.15.2"
