name = "modfest-skyandsea"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash = "560f832edccbaaecfd24cbd80eb1ba12f347ca438963c7ebad4ae1fda6004717"
hash-format = "sha256"
metafile = false
preserve = false

[versions]
fabric = "0.15.3"
minecraft = "1.20.4"
