name = "modfest-skyandsea"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash = "8cedf04204afecff69ea81d6ba2fb8adbc6977a95e46b3db4a5201b4cef32742"
hash-format = "sha256"
metafile = false
preserve = false

[versions]
minecraft = "1.20.4"
fabric = "0.15.3"
