name = "modfest-skyandsea"
version = "496a9faabbd5c5971d48969a076dfbba2f83aa0a"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash = "dc75165b9736e8f90a5ac03fc2c91a3baa8f9dfebf1c4688a0329d207f76f8f0"
hash-format = "sha256"
metafile = false
preserve = false

[versions]
fabric = "0.15.2"
minecraft = "1.20.4"
