name = "modfest-skyandsea"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash = "fcb51c6730c9021a770fc186ad355e68da4815f63605d892be84331b1543e716"
hash-format = "sha256"
metafile = false
preserve = false

[versions]
fabric = "0.15.3"
minecraft = "1.20.4"
