name = "modfest-skyandsea"
version = "4cfdd97358d3a29e218e3c2fff3e05f4bcc03e7d"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash = "723a4a1b3535e8a8d04b5629d447aeef116924fabf77287e16e21a70d0c79b8e"
hash-format = "sha256"
metafile = false
preserve = false

[versions]
minecraft = "1.20.4"
fabric = "0.15.1"
