name = "modfest-skyandsea"
version = "e9b2b0119c59a87e94211d71d4231a0edf741ebc"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash = "3ceff254a3cc40c90873ccbc12e0e2abd8cda9f0ba04785e77f0f0721cd55e0a"
hash-format = "sha256"
metafile = false
preserve = false

[versions]
minecraft = "1.20.4"
fabric = "0.15.3"
