name = "modfest-skyandsea"
version = "db755bff8963728987ce66fa053213a6a32bfae5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash = "229fbdbdb41994e7871dd5b685ab05d0fc066626be86fa43ed55c8b3fcf67682"
hash-format = "sha256"
metafile = false
preserve = false

[versions]
minecraft = "1.20.4"
fabric = "0.15.2"
