name = "modfest-skyandsea"
version = "ad4b7c8d35570b3e7fde98ebd3592ba0e646054c"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash = "69b07cc8eb0e830369c730d86c6d4fad8a50c6ecdfccb8e5fc5774efe199c328"
hash-format = "sha256"
metafile = false
preserve = false

[versions]
fabric = "0.15.3"
minecraft = "1.20.4"
