name = "modfest-skyandsea"
version = "6a46bf55d6ecc2995416dc82373a9fda1dca63c1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash = "a3b6e8e2e1b5aec91e2be6c32fa097474d929f50c37fb05af7fc7254fdde266b"
hash-format = "sha256"
metafile = false
preserve = false

[versions]
minecraft = "1.20.4"
fabric = "0.15.2"
