name: Update Instance

on:
  push:
    branches:
      - main
    paths:
      - profile/**

jobs:
  update-instance:
    runs-on: ubuntu-latest

    permissions:
      pages: write
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Zip profile directory
      run: zip -r profile.zip profile/

    - name: Publish to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
        publish_branch: gh-pages
        destination_dir: content
        keep_files: true
        commit_message: "Publish profile to GitHub Pages"
